services:
  kallia-api:
    build: .
    container_name: kallia-api
    restart: always
    ports:
      - "1904:1904"
    volumes:
      - .:/app
      - ../Databases:/Databases
    env_file:
      - .env
